# Generated by Django 4.1.3 on 2022-11-11 13:41

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("model", models.CharField(max_length=60)),
                ("brand", models.CharField(max_length=60)),
                ("color", models.CharField(max_length=15)),
                ("city", models.CharField(max_length=60)),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("New", "New"),
                            ("Used", "Used"),
                            ("Not specified", "Default"),
                        ],
                        max_length=13,
                    ),
                ),
                (
                    "plate",
                    models.CharField(
                        max_length=7,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(limit_value=7)
                        ],
                    ),
                ),
                ("photo", models.CharField(max_length=200)),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
