import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import { CarCard } from "../../components/common/carCard";
import useSWR from "swr";


export default function QueryPage() {

  const fetcher = (...args) => fetch(...args).then((res) => res.json());
  const router = useRouter();
  const page = router.query.id;

  const { data, error } = useSWR(
    `http://127.0.0.1:8000/api/vehicles/?${page}`,
    fetcher
  );
  

  return (
    <>
      <Head>
        <title>Vitrine</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="grid gap-2 px-5 py-3 rounded-md max-w-[1200px] lg:mx-auto">
        <h2 className="uppercase font-light col-span-2">Carros usados</h2>
        <div className="container-carros">
          {!data ? (
            <>
              <div>Loading...</div>
            </>
          ) : (
            <>
              {" "}
              <ul className="grid sm:grid-cols-2 lg:grid-cols-4 gap-5">
                {data?.results.map((car: any) => (
                  <CarCard car={car} key={car.id} />
                ))}
              </ul>
            </>
          )}
        </div>
      </div>
      <div className="container-pages flex justify-center gap-3 px-5 py-3 rounded-md max-w-[1200px] lg:mx-auto">
        {data?.previous && (
          <Link
            className="bg-customBlack-300 py-2 px-5 text-white font-bold rounded-sm"
            href={ data?.previous?.split("?")[1] !== undefined ? `/carros-usados/${data?.previous?.split("?")[1]}` : `/carros-usados/`}
          >
            Anterior
          </Link>
        )}
        {data?.next && (
          <Link
            className="bg-customBlack-300 py-2 px-5 text-white font-bold rounded-sm"
            href={`/carros-usados/${data?.next?.split("?")[1]}`}
          >
            Próxima
          </Link>
        )}
      </div>
    </>
  );
}
