import Head from "next/head";
import { Form } from "../../components/common/form";

export default function LoginPage() {
  return (
    <div className="p-4 max-w-[1200px] lg:mx-auto">
      <Head>
        <title>Iniciar sessão</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="max-w-xl mx-auto">
        <h2 className="text-3xl text-neutral-800 font-bold tracking-tight mt-10 mb-1">
          Iniciar sessão
        </h2>
        <p className="text-neutral-400 mb-5">
          Insira seu email e senha para iniciar sua sessão
        </p>
      </div>
      <div>
        <Form formType="login" />
      </div>
    </div>
  );
}
