import Head from "next/head";
import Link from "next/link";
import { ReasonCard } from "../components/common/reasonCard";

export default function Home() {
  const reasons = [{ id: 0 }, { id: 1 }, { id: 2 }];

  return (
    <>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex flex-col items-center bg-blue-400 px-5 py-10">
        <h2 className="font-extrabold text-2xl text-white">Transformando a</h2>
        <h2 className="font-extrabold text-2xl text-white">
          compra e venda de
        </h2>
        <h2 className="font-extrabold text-2xl text-white mb-5">
          carros usados no Brasil
        </h2>
        <Link
          href="/carros-usados"
          className="inline-block mx-auto text-center bg-white py-4 px-20 rounded-md border text-black font-semibold"
        >
          Veja nosso catálogo
        </Link>
      </div>
      <div className="p-5 max-w-[1200px] lg:mx-auto text-center">
        <h3 className="text-3xl font-bold lg:text-4xl lg:font-extrabold">
          3 Razoes para escolhar comprar um carro na PLACEHOLDER
        </h3>
      </div>
      <div className="p-5 max-w-[1200px] lg:mx-auto">
        <ul className="grid sm:grid-cols-2 lg:grid-cols-3 gap-3">
          {reasons.map((reason) => (
            <ReasonCard key={reason.id} reason={reason} />
          ))}
        </ul>
      </div>
    </>
  );
}
